apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-server
  namespace: argo
rules:
- apiGroups: ["argoproj.io"]
  resources: ["pods", "workflows", "workflowtemplates", "cronworkflows", "workfloweventbindings", "eventsources", "sensors"]
  verbs: ["get", "watch", "patch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-server
  namespace: argo
roleRef:
  kind: Role
  name: argo-server
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: argo-server
  namespace: argo
